### ISSUE TITLE
How can i change the templates?

### ISSUE THREAD

**Issue by ragsnas** [wcandillon/grunt-swagger-js-codegen#22]
I need to modify the templates.
Can i and "How can i" configure grunt-swagger-js-codegen to user different templates than the ones in the node_modules folder?

**Comment by wcandillon** [comment]
There is an `template` and `custom` parameter see https://github.com/wcandillon/grunt-swagger-js-codegen/blob/master/tasks/swagger-js-codegen.js#L34

**Comment by ragsnas** [comment]
The Problem is, if i use custom, it expects the template parameters (class, method, request) to be the strings.
If i load the template fully (using fs in the Gruntfile) something happens in the process (html entities) and handlebar can not parse them anymore.
It would be more natural and easy to define filenames, rather than the full template in the Gruntfile.
I made the respective changes in my forks of the project.
https://github.com/ragsnas/grunt-swagger-js-codegen
https://github.com/ragsnas/swagger-js-codegen
Having to Pull Requests is a bit much thou innit?

**Comment by wcandillon** [comment]
@ragsnas I think it would be less flexible to had a dependency with the filesystem there. What happens if  the templates are loaded from http? I think it would be more interesting to investigating the issue you are having with the templates being encoded. Is there an example I could look at?
